fun main(): void {
  print_string("This file has non-printable characters. Be careful editing!");
  print_raw(
    String::fromChars(
      Array[
        '\a',
        '\b',
        '\e',
        '\f',
        '\n',
        '\r',
        '\t',
        '\v',
        '\\',
        '\'',
        '\"',
        '\n',
        '\x48',
        '\x65',
        '\x6c',
        '\x6c',
        '\x6f',
        '\x20',
        '\x77',
        '\x6f',
        '\x72',
        '\x6c',
        '\x64',
        '\x21',
        '\n',
        // TODO backends do no support unicode characters yet
        // '\n',
        // '\u00AF',
        // '\\',
        // '_',
        // '(',
        // '\u30C4',
        // ')',
        // '_',
        // '/',
        // '\u00AF',
        // '\n',
        // '\U0001F602'
      ],
    ),
  )
}
