/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

@cpp_export_as("mkVec")
fun mkVec(n: Float): mutable Vector<Int> {
  Vector::mfillBy(n.toInt(), i -> i)
}

@cpp_export_as("sk.main")
fun main(): void {
  v = mkVec(5.0);
  for (elem in v) {
    print_raw(elem.toString() + "\n");
  };
  void
}
