class EqString(str: String) uses Equality {
  fun ==(b: EqString): Bool {
    this.str == b.str
  }
}

@test
fun testToString(): void {
  assertEqual(Null().toString(), "Null()");
  assertEqual(Box(1).toString(), "Box(1)");
}

@test
fun testEqual(): void {
  a: Nullable<EqString> = Box(EqString("a"));
  a2: Nullable<EqString> = Box(EqString("a"));
  b: Nullable<EqString> = Box(EqString("b"));
  null: Nullable<EqString> = Null();
  null2: Nullable<EqString> = Null();
  assertTrue(a == a);
  assertTrue(a == a2);
  assertFalse(a == b);
  assertTrue(null == null);
  assertTrue(null == null2);
  assertFalse(a == null);

  assertFalse(a != a);
  assertFalse(a != a2);
  assertTrue(a != b);
  assertFalse(null != null);
  assertFalse(null != null2);
  assertTrue(a != null);
}

@test
fun testNullableTest(): void {
  a: Nullable<String> = Box("a");
  null: Nullable<String> = Null();
  assertTrue(a.test(x -> x == "a"));
  assertFalse(a.test(x -> x == "b"));
  assertFalse(null.test(x -> x == "a"))
}
