base class A(a: Int, b: String)
class B extends A

fun myMatch(x: A): String {
  x match {
  | A(1, "a") -> "P"
  | A(2, _) -> "a"
  | A(_, "b") -> "s"
  | A(42, "c") -> "s"
  | A _ -> "\n"
  }
}

fun main(): void {
  p = B(1, "a");
  a = B(2, "hi!");
  s1 = B(42, "b");
  s2 = B(42, "c");
  newline = B(56, "Hello!");
  print_raw(
    myMatch(p) + myMatch(a) + myMatch(s1) + myMatch(s2) + myMatch(newline),
  )
}
