/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

/*****************************************************************************/
/* Entry point used for typechecking. Invoke it as
 *
 *     skip_check [ROOT_DIR | FILE]
 *
 * It will search upward from the given root path (or the current directory) for a
 * .skipconfig file. See skipConfig.ml for more.
 */
/*****************************************************************************/

untracked fun main(): void {
  print_raw(
    SkipError.errorsToString(
      SkipAnalyze.analyzeFile(false, SkipAnalyze.pathOfArguments()),
    ),
  )
}
