/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

// Main entrypoint for Nuclide LSP provider for Skip.
// Implementation of the VS Code Language Server Protocol
// https://github.com/Microsoft/language-server-protocol/blob/gh-pages/specification.md

class LSPArguments{includeTypeErrors: Bool = true, testMode: Bool = false}

untracked fun main(): void {
  (args, _files, _unknownArguments) = Arguments.parse(
    LSPArguments{},
    List[
      (
        "--no-type-errors",
        Arguments.SetTrue(args ~> args with {includeTypeErrors => false}),
      ),
      ("--test-mode", Arguments.SetTrue(args ~> args with {testMode => true})),
    ],
    "Usage: skip_lsp [--no-type-errors] [--test-mode]",
  );

  server = mutable LspServer{
    includeTypeErrors => args.includeTypeErrors,
    reportDoneProcessing => args.testMode,
    enableConsole => !args.testMode,
    enableLogging => !args.testMode,
  };
  exit(server.run());
}
