/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

untracked fun main(): void {
  contents = read_stdin();
  parsed = SkipParser.parseSource(contents, false);

  if (parsed.errors.size() > 0) {
    print_error_ln("Syntax Error! " + parsed.errors[0]);
    print_raw(contents);
    exit(1)
  } else {
    ctx = SkipPrinter.Context{contents};
    Doc.printDoc(SkipPrinter.print(ctx, parsed.tree), print_raw);
    print_raw("\n")
  };
  void
}
