module Orderable;

/*
 * Classes that provide a total order, in the standard sense.  (So,
 * for example, this does not include floating point.)
 */
trait .Orderable extends Equality {
  readonly fun compare(inst): Order;

  overridable readonly fun ==(other: inst): Bool {
    this.compare(other) == EQ()
  }

  overridable readonly fun <(other: inst): Bool {
    this.compare(other) == LT()
  }

  overridable readonly fun >(other: inst): Bool {
    this.compare(other) == GT()
  }

  overridable readonly fun <=(other: inst): Bool {
    this.compare(other) != GT()
  }

  overridable readonly fun >=(other: inst): Bool {
    this.compare(other) != LT()
  }
}

fun .compare<T: Orderable>(x: T, y: T): Order {
  x.compare(y)
}

// Given a value (typically non-Orderable) and comparison function,
// create an Orderable-compatible value. This function is typically
// used with collection sortBy/sortedBy methods:
//
//    a: Vector<NonOrderable> = Vector[...];
//    compare = (a: NonOrderable, b: NonOrderable): Order ~> { ... };
//    b = a.sortedBy(x ~> Orderable.create(x, compare));
// ```
fun create<T>(value: T, compare: (T, T) ~> Order): LambdaOrderable<T> {
  LambdaOrderable(value, compare)
}

private value class LambdaOrderable<T>(
  value: T,
  compareFn: (T, T) ~> Order,
) uses Orderable {
  fun compare(other: this): Order {
    this.compareFn(this.value, other.value);
  }

  fun ==(other: this): Bool {
    this.compare(other) is EQ();
  }

  fun !=(other: this): Bool {
    !(this == other);
  }

  fun <(other: this): Bool {
    this.compare(other) == LT()
  }

  fun >(other: this): Bool {
    this.compare(other) == GT()
  }

  fun <=(other: this): Bool {
    this.compare(other) != GT()
  }

  fun >=(other: this): Bool {
    this.compare(other) != LT()
  }
}

module end;
