/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

native value class Int8 uses Integral {
  @intrinsic
  native fun toInt(): Int;
  @intrinsic
  native static fun truncate(n: Int): Int8;
  const min: Int8 = Int8::truncate(-0x80);
  const max: Int8 = Int8::truncate(0x7F);
}
