/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

value class UInt8 private (private value: Int8) uses Integral {
  fun toInt(): Int {
    this.value.and(0xFF)
  }
  static fun truncate(n: Int): UInt8 {
    UInt8(Int8::truncate(n))
  }
  const min: UInt8 = UInt8::truncate(0);
  const zero: UInt8 = UInt8::truncate(0);
  const max: UInt8 = UInt8::truncate(0xFF);
}
