#!/bin/bash

diff -r -X $(dirname $0)/../.gitignore --brief $1 $2 > /dev/null
if [ $? -ne 0 ]; then
  echo "Runtimes '$1' and '$2' differ."
  echo "Sync them (possibly with 'tools/sync-runtime')."
  exit 1
else
  echo "Runtimes '$1' and '$2' are in sync."
fi
