--- test_params1
fun callFunction(null, "fn1"): void
fun callFunction(null, "fn1_b", <bool> true): void
fun callFunction(null, "fn1_b", <bool> false): void
fun callFunction(null, "fn1_i", <int64> 42): void
fun callFunction(null, "fn1_f", <float64> 3.125000): void
fun callFunction(null, "fn1_s", <string> "short"): void
fun callFunction(null, "fn1_s", <string> "this is a long string"): void
fun callFunction(null, "fn1_o1", object<<no type>>): void
fun callFunction(null, "fn1_o2", object<HhvmObject2_A>): void
fun callFunction(null, "fn1_a", array<HH_varray>): void
fun callFunction(null, "fn1_shape", array<HhvmShape1>): void
SKIP_HhvmInterop_ShapeCons_create(HhvmShape2)
SKIP_HhvmInterop_ShapeCons_setFieldMixed(array<HhvmShape2>, a, 1)
SKIP_HhvmInterop_ShapeCons_setFieldMixed(array<HhvmShape2>, b, 2)
SKIP_HhvmInterop_ShapeCons_finish(array<HhvmShape2>)
fun callFunction(null, "fn1_shape2", array<HhvmShape2>): void
SKIP_HhvmInterop_ObjectCons_create(HhvmObject7)
SKIP_HhvmInterop_ObjectCons_setFieldMixed(object<HhvmObject7>, a, 1)
SKIP_HhvmInterop_ObjectCons_setFieldMixed(object<HhvmObject7>, b, 2)
SKIP_HhvmInterop_ObjectCons_finish(object<HhvmObject7>)
fun callFunction(null, "fn1_o7", object<HhvmObject7>): void
fun callFunction(null, "fn1_m", <mixed> null): void
fun callFunction(null, "fn1_m", <mixed> 123): void
fun callFunction(null, "fn1_m", <mixed> 'abcd'): void
HH_varray::internalCreate()
HH_varray::append(array<varray>, 12)
HH_varray::append(array<varray>, 13)
fun callFunction(null, "fn1_tup", array<varray>): void
--- test_params2
fun callFunction(null, "fn2_b", <?bool> null): void
fun callFunction(null, "fn2_i", <?int64> null): void
fun callFunction(null, "fn2_f", <?float64> null): void
fun callFunction(null, "fn2_s", <?string> null): void
fun callFunction(null, "fn2_o1", <?object> null): void
fun callFunction(null, "fn2_o2", <?object> null): void
fun callFunction(null, "fn2_a", <?array> null): void
fun callFunction(null, "fn2_b", <?bool> true): void
fun callFunction(null, "fn2_b", <?bool> false): void
fun callFunction(null, "fn2_i", <?int64> 42): void
fun callFunction(null, "fn2_f", <?float64> 3.125000): void
fun callFunction(null, "fn2_s", <?string> "short"): void
fun callFunction(null, "fn2_s", <?string> "this is a long string"): void
fun callFunction(null, "fn2_o1", <?object> object<<no type>>): void
fun callFunction(null, "fn2_o2", <?object> object<HhvmObject2_A>): void
fun callFunction(null, "fn2_a", <?array> array<HH_varray>): void
--- test_params3
fun callFunction(null, "Params3.fn_b", <?bool> null): void
fun callFunction(null, "Params3.fn_b", <?bool> false): void
fun callFunction(null, "Params3.fn_b", <?bool> true): void
fun callFunction(null, "Params3.fn_i", <?int64> null): void
fun callFunction(null, "Params3.fn_i", <?int64> 42): void
fun callFunction(null, "Params3.fn_f", <?float64> null): void
fun callFunction(null, "Params3.fn_f", <?float64> 3.500000): void
fun callFunction(null, "Params3.fn_s", <?string> null): void
fun callFunction(null, "Params3.fn_s", <?string> "short"): void
fun callFunction(null, "Params3.fn_s", <?string> "this is a long string"): void
fun callFunction(null, "Params3.fn_o1", <?object> null): void
fun callFunction(null, "Params3.fn_o1", <?object> object<<no type>>): void
fun callFunction(null, "Params3.fn_o2", <?object> null): void
fun callFunction(null, "Params3.fn_o2", <?object> object<HhvmObject2_A>): void
fun callFunction(null, "Params3.fn_a", <?array> null): void
fun callFunction(null, "Params3.fn_a", <?array> array<HH_varray>): void
fun callFunction(null, "Params3.fn_o7", <?object> null): void
SKIP_HhvmInterop_ObjectCons_create(HhvmObject7)
SKIP_HhvmInterop_ObjectCons_setFieldMixed(object<HhvmObject7>, a, 1)
SKIP_HhvmInterop_ObjectCons_setFieldMixed(object<HhvmObject7>, b, 2)
SKIP_HhvmInterop_ObjectCons_finish(object<HhvmObject7>)
fun callFunction(null, "Params3.fn_o7", <?object> object<HhvmObject7>): void
fun callFunction(null, "Params3.fn_shape1", <?array> null): void
fun callFunction(null, "Params3.fn_shape1", <?array> array<HhvmShape1>): void
fun callFunction(null, "Params3.fn_shape2", <?array> null): void
SKIP_HhvmInterop_ShapeCons_create(HhvmShape2)
SKIP_HhvmInterop_ShapeCons_setFieldMixed(array<HhvmShape2>, a, 1)
SKIP_HhvmInterop_ShapeCons_setFieldMixed(array<HhvmShape2>, b, 2)
SKIP_HhvmInterop_ShapeCons_finish(array<HhvmShape2>)
fun callFunction(null, "Params3.fn_shape2", <?array> array<HhvmShape2>): void
--- test_returns
fun callFunction(null, "fn3_b"): Bool
b: false
fun callFunction(null, "fn3_b"): Bool
b: true
fun callFunction(null, "fn3_i"): Int
i: 42
fun callFunction(null, "fn3_f"): Float
f: 3.125
fun callFunction(null, "fn3_s"): String
s: short
fun callFunction(null, "fn3_s"): String
s: this is a long string
fun callFunction(null, "fn3_o1"): HhvmObject
o1: HhvmObject1
fun callFunction(null, "fn3_o2"): HhvmObject
o2: HhvmObject2_A
fun callFunction(null, "fn3_o7"): HhvmObject
getField(wrapper: object<HhvmObject7>, field: 'a')
getField(wrapper: object<HhvmObject7>, field: 'b')
o7: HhvmObject7(10, 20)
fun callFunction(null, "fn3_a"): array
a: HH_varray<>#Array1
fun callFunction(null, "fn3_shape"): array
shape: HhvmShape1
fun callFunction(null, "fn3_shape2"): array
getField<shape>(wrapper: array<HhvmShape2>, field: 'a')
getField<shape>(wrapper: array<HhvmShape2>, field: 'b')
shape2: HhvmShape2(21, 22)
fun callFunction(null, "Returns1.fn_mixed"): HH.Mixed
mixed: HH.Null
fun callFunction(null, "Returns1.fn_mixed"): HH.Mixed
mixed: HH.Int(123)
fun callFunction(null, "Returns1.fn_mixed"): HH.Mixed
mixed: HH.String(hello, world)
fun callFunction(null, "fn3_tuple"): array
SKIP::Vector::HH_varray::get(array<Tuple>, 0)
SKIP::Vector::HH_varray::get(array<Tuple>, 1)
tuple: (22, 23)
--- Returns2
fun callFunction(null, "fn3_nb"): ?Bool
b: Null()
fun callFunction(null, "fn3_ni"): ?Int
i: Null()
fun callFunction(null, "fn3_nf"): ?Float
f: Null()
fun callFunction(null, "fn3_ns"): ?String
s: Null()
fun callFunction(null, "fn3_no1"): ?HhvmObject
o1: Null()
fun callFunction(null, "fn3_no2"): ?HhvmObject
o2: Null()
fun callFunction(null, "fn3_na"): ?array
a: Null()
fun callFunction(null, "fn3_nshape"): ?array
shape: Null()
fun callFunction(null, "fn3_nb"): ?Bool
b: Box(false)
fun callFunction(null, "fn3_nb"): ?Bool
b: Box(true)
fun callFunction(null, "fn3_ni"): ?Int
i: Box(42)
fun callFunction(null, "fn3_nf"): ?Float
f: Box(3.125)
fun callFunction(null, "fn3_ns"): ?String
s: Box(short)
fun callFunction(null, "fn3_ns"): ?String
s: Box(this is a long string)
fun callFunction(null, "fn3_no1"): ?HhvmObject
o1: Box(HhvmObject1)
fun callFunction(null, "fn3_no2"): ?HhvmObject
o2: Box(HhvmObject2_B)
fun callFunction(null, "fn3_na"): ?array
a: Box(HH_varray<>#Array3)
fun callFunction(null, "fn3_nshape"): ?array
shape: Null()
fun callFunction(null, "fn3_nshape"): ?array
shape: Box(HhvmShape1)
--- Returns3
fun callFunction(null, "Returns3.fn_b"): ?Bool
b0: None()
fun callFunction(null, "Returns3.fn_b"): ?Bool
b1: Some(true)
fun callFunction(null, "Returns3.fn_b"): ?Bool
b2: Some(false)
fun callFunction(null, "Returns3.fn_i"): ?Int
i0: None()
fun callFunction(null, "Returns3.fn_i"): ?Int
i1: Some(123)
fun callFunction(null, "Returns3.fn_f"): ?Float
f0: None()
fun callFunction(null, "Returns3.fn_f"): ?Float
f1: Some(3.5)
fun callFunction(null, "Returns3.fn_s"): ?String
s0: None()
fun callFunction(null, "Returns3.fn_s"): ?String
s1: Some(short)
fun callFunction(null, "Returns3.fn_s"): ?String
s2: Some(this is a long string)
fun callFunction(null, "Returns3.fn_o1"): ?HhvmObject
o1: None()
fun callFunction(null, "Returns3.fn_o1"): ?HhvmObject
o1: Some(HhvmObject1)
fun callFunction(null, "Returns3.fn_o2"): ?HhvmObject
o2: None()
fun callFunction(null, "Returns3.fn_o2"): ?HhvmObject
o2: Some(HhvmObject2_B)
fun callFunction(null, "Returns3.fn_o7"): ?HhvmObject
o7: None()
fun callFunction(null, "Returns3.fn_o7"): ?HhvmObject
getField(wrapper: object<HhvmObject7>, field: 'a')
getField(wrapper: object<HhvmObject7>, field: 'b')
o7: Some(HhvmObject7(10, 20))
fun callFunction(null, "Returns3.fn_a"): ?array
shape1: None()
fun callFunction(null, "Returns3.fn_a"): ?array
shape1: Some(HH_varray<>#Array1)
fun callFunction(null, "Returns3.fn_shape1"): ?array
shape1: None()
fun callFunction(null, "Returns3.fn_shape1"): ?array
shape1: Some(HhvmShape1)
fun callFunction(null, "Returns3.fn_shape2"): ?array
shape2: None()
fun callFunction(null, "Returns3.fn_shape2"): ?array
getField<shape>(wrapper: array<HhvmShape2>, field: 'a')
getField<shape>(wrapper: array<HhvmShape2>, field: 'b')
shape2: Some(HhvmShape2(21, 22))
--- test_methods
fun callFunction(object<<no type>>, "method1"): void
fun callFunction(null, "HhvmObject3::staticMethod1"): void
fun callFunction(object<HhvmObject4>, "method1"): void
--- test_getters
getField(wrapper: object<<no type>>, field: 'field_bool')
field_bool: false
getField(wrapper: object<<no type>>, field: 'field_bool')
field_bool: true
getField(wrapper: object<<no type>>, field: 'field_int')
field_int: 42
getField(wrapper: object<<no type>>, field: 'field_float')
field_float: 3.125
getField(wrapper: object<<no type>>, field: 'field_string')
field_string: hello
getField(wrapper: object<<no type>>, field: 'field_object1')
field_object: <object6:<no type>>
getField(wrapper: object<<no type>>, field: 'field_object2')
field_object: HhvmObject2_B
getField(wrapper: object<<no type>>, field: 'field_arrayKey')
field_arrayKey: 123
getField(wrapper: object<<no type>>, field: 'field_arrayKey')
field_arrayKey: hello
getField(wrapper: object<<no type>>, field: 'field_nonnull')
field_nonnull: HH.Int(123)
getField(wrapper: object<<no type>>, field: 'field_nullable_bool')
field_nullable_bool: Null()
getField(wrapper: object<<no type>>, field: 'field_nullable_bool')
field_nullable_bool: Box(false)
getField(wrapper: object<<no type>>, field: 'field_nullable_bool')
field_nullable_bool: Box(true)
getField(wrapper: object<<no type>>, field: 'field_nullable_int')
field_nullable_int: Null()
getField(wrapper: object<<no type>>, field: 'field_nullable_int')
field_nullable_int: Box(42)
getField(wrapper: object<<no type>>, field: 'field_nullable_float')
field_nullable_float: Null()
getField(wrapper: object<<no type>>, field: 'field_nullable_float')
field_nullable_float: Box(3.125)
getField(wrapper: object<<no type>>, field: 'field_nullable_string')
field_nullable_string: Null()
getField(wrapper: object<<no type>>, field: 'field_nullable_string')
field_nullable_string: Box(hello)
getField(wrapper: object<<no type>>, field: 'field_nullable_object1')
field_nullable_object: Null()
getField(wrapper: object<<no type>>, field: 'field_nullable_object1')
field_nullable_object: Box(<object6:<no type>>)
getField(wrapper: object<<no type>>, field: 'field_nullable_object2')
field_nullable_object: Null()
getField(wrapper: object<<no type>>, field: 'field_nullable_object2')
field_nullable_object: Box(HhvmObject2_B)
getField(wrapper: object<<no type>>, field: 'field_nullable_arrayKey')
field_nullable_arrayKey: Null()
getField(wrapper: object<<no type>>, field: 'field_nullable_arrayKey')
field_nullable_arrayKey: Box(234)
getField(wrapper: object<<no type>>, field: 'field_nullable_arrayKey')
field_nullable_arrayKey: Box(there)
getField<shape>(wrapper: array<HhvmShape1>, field: 'a')
shape: 345
--- test_setters
setField(wrapper: object<<no type>>, field: 'field_bool', value: false)
setField(wrapper: object<<no type>>, field: 'field_bool', value: true)
setField(wrapper: object<<no type>>, field: 'field_int', value: 42)
setField(wrapper: object<<no type>>, field: 'field_float', value: -6.250000)
setField(wrapper: object<<no type>>, field: 'field_string', value: 'short')
setField(wrapper: object<<no type>>, field: 'field_string', value: 'this is a long string')
setField(wrapper: object<<no type>>, field: 'field_object1', value: object<<no type>>)
setField(wrapper: object<<no type>>, field: 'field_object2', value: object<HhvmObject2_A>)
setField(wrapper: object<<no type>>, field: 'field_arrayKey', value: 123)
setField(wrapper: object<<no type>>, field: 'field_arrayKey', value: 'abc')
setField(wrapper: object<<no type>>, field: 'field_arrayKey', value: '123')
setField(wrapper: object<<no type>>, field: 'field_arrayKey', value: 234)
setField(wrapper: object<<no type>>, field: 'field_arrayKey', value: 'def')
setField(wrapper: object<<no type>>, field: 'field_nonnull', value: false)
setField(wrapper: object<<no type>>, field: 'field_nonnull', value: 17)
setField(wrapper: object<<no type>>, field: 'field_nonnull', value: 3.250000)
setField(wrapper: object<<no type>>, field: 'field_nonnull', value: 'hello')
setField(wrapper: object<<no type>>, field: 'field_nullable_bool', value: null)
setField(wrapper: object<<no type>>, field: 'field_nullable_bool', value: false)
setField(wrapper: object<<no type>>, field: 'field_nullable_bool', value: true)
setField(wrapper: object<<no type>>, field: 'field_nullable_int', value: null)
setField(wrapper: object<<no type>>, field: 'field_nullable_int', value: 42)
setField(wrapper: object<<no type>>, field: 'field_nullable_float', value: null)
setField(wrapper: object<<no type>>, field: 'field_nullable_float', value: -6.250000)
setField(wrapper: object<<no type>>, field: 'field_nullable_string', value: null)
setField(wrapper: object<<no type>>, field: 'field_nullable_string', value: 'short')
setField(wrapper: object<<no type>>, field: 'field_nullable_string', value: 'this is a long string')
setField(wrapper: object<<no type>>, field: 'field_nullable_object1', value: null)
setField(wrapper: object<<no type>>, field: 'field_nullable_object1', value: object<<no type>>)
setField(wrapper: object<<no type>>, field: 'field_nullable_object2', value: null)
setField(wrapper: object<<no type>>, field: 'field_nullable_object2', value: object<HhvmObject2_A>)
setField(wrapper: object<<no type>>, field: 'field_nullable_arrayKey', value: null)
setField(wrapper: object<<no type>>, field: 'field_nullable_arrayKey', value: 123)
setField(wrapper: object<<no type>>, field: 'field_nullable_arrayKey', value: 'abc')
setField(wrapper: object<<no type>>, field: 'field_nullable_mixed', value: null)
setField(wrapper: object<<no type>>, field: 'field_nullable_mixed', value: 123)
--- test_inherit
<A:A>
<B:B>
<C:C>
caught runtime error: unknown hhvm type: 'D' on base class 'B'
--- CommonBase.test1
getField(wrapper: object<CommonBase::Import>, field: 'a')
getField(wrapper: object<CommonBase::Import>, field: 'b')
getField(wrapper: object<CommonBase::Import>, field: 'c')
Import: Import{a => 1001, b => 1002, c => 1003}
getField(wrapper: object<CommonBase::Import>, field: 'a')
getField(wrapper: object<CommonBase::Import>, field: 'b')
getField(wrapper: object<CommonBase::Import>, field: 'c')
Common: Import{a => 1001, b => 1002, c => 1003}
getField(wrapper: object<CommonBase::Copy>, field: 'a')
getField(wrapper: object<CommonBase::Copy>, field: 'b')
getField(wrapper: object<CommonBase::Copy>, field: 'c')
Copy: Copy{a => 2001, b => 2002, c => 2003}
Common: Copy{a => 2001, b => 2002, c => 2003}
