Int s1: true
Int s2: true
Int s3: true
Int s4: true
Int s5: true
Int s6: true
Int n1: false
Int n2: false
Int n3: false
Int n4: true
Int ts1: true
Int ts2: true
Int ts3: true
Int ts4: true
Int ts5: true
Int ts6: true
Int xs1: true
Int xs2: true
Int xs3: true
Int xs4: true
Int xs5: true
Int xs6: true
String s1: true
String s2: true
String s3: true
String s4: true
String s5: true
String s6: true
String n1: false
String n2: false
String n3: false
String n4: true
String ts1: true
String ts2: true
String ts3: true
String ts4: true
String ts5: true
String ts6: true
String xs1: true
String xs2: true
String xs3: true
String xs4: true
String xs5: true
String xs6: true
?Int 1 s1: true
?Int 1 s2: true
?Int 1 s3: true
?Int 1 s4: true
?Int 1 s5: true
?Int 1 s6: true
?Int 1 n1: false
?Int 1 n2: false
?Int 1 n3: false
?Int 1 n4: true
?Int 1 ts1: true
?Int 1 ts2: true
?Int 1 ts3: true
?Int 1 ts4: true
?Int 1 ts5: true
?Int 1 ts6: true
?Int 1 xs1: true
?Int 1 xs2: true
?Int 1 xs3: true
?Int 1 xs4: true
?Int 1 xs5: true
?Int 1 xs6: true
?Int 2 s1: true
?Int 2 s2: true
?Int 2 s3: true
?Int 2 s4: true
?Int 2 s5: true
?Int 2 s6: true
?Int 2 n1: false
?Int 2 n2: false
?Int 2 n3: false
?Int 2 n4: true
?Int 2 ts1: true
?Int 2 ts2: true
?Int 2 ts3: true
?Int 2 ts4: true
?Int 2 ts5: true
?Int 2 ts6: true
?Int 2 xs1: true
?Int 2 xs2: true
?Int 2 xs3: true
?Int 2 xs4: true
?Int 2 xs5: true
?Int 2 xs6: true
?Int 3 s1: true
?Int 3 s2: true
?Int 3 s3: true
?Int 3 s4: true
?Int 3 s5: true
?Int 3 s6: true
?Int 3 n1: false
?Int 3 n2: false
?Int 3 n3: false
?Int 3 n4: true
?Int 3 ts1: true
?Int 3 ts2: true
?Int 3 ts3: true
?Int 3 ts4: true
?Int 3 ts5: true
?Int 3 ts6: true
?Int 3 xs1: true
?Int 3 xs2: true
?Int 3 xs3: true
?Int 3 xs4: true
?Int 3 xs5: true
?Int 3 xs6: true
?Int 4 s1: true
?Int 4 s2: true
?Int 4 s3: true
?Int 4 s4: true
?Int 4 s5: true
?Int 4 s6: true
?Int 4 n1: false
?Int 4 n2: false
?Int 4 n3: false
?Int 4 n4: true
?Int 4 ts1: true
?Int 4 ts2: true
?Int 4 ts3: true
?Int 4 ts4: true
?Int 4 ts5: true
?Int 4 ts6: true
?Int 4 xs1: true
?Int 4 xs2: true
?Int 4 xs3: true
?Int 4 xs4: true
?Int 4 xs5: true
?Int 4 xs6: true
?String 1 s1: true
?String 1 s2: true
?String 1 s3: true
?String 1 s4: true
?String 1 s5: true
?String 1 s6: true
?String 1 n1: false
?String 1 n2: false
?String 1 n3: false
?String 1 n4: true
?String 1 ts1: true
?String 1 ts2: true
?String 1 ts3: true
?String 1 ts4: true
?String 1 ts5: true
?String 1 ts6: true
?String 1 xs1: true
?String 1 xs2: true
?String 1 xs3: true
?String 1 xs4: true
?String 1 xs5: true
?String 1 xs6: true
?String 2 s1: true
?String 2 s2: true
?String 2 s3: true
?String 2 s4: true
?String 2 s5: true
?String 2 s6: true
?String 2 n1: false
?String 2 n2: false
?String 2 n3: false
?String 2 n4: true
?String 2 ts1: true
?String 2 ts2: true
?String 2 ts3: true
?String 2 ts4: true
?String 2 ts5: true
?String 2 ts6: true
?String 2 xs1: true
?String 2 xs2: true
?String 2 xs3: true
?String 2 xs4: true
?String 2 xs5: true
?String 2 xs6: true
?String 3 s1: true
?String 3 s2: true
?String 3 s3: true
?String 3 s4: true
?String 3 s5: true
?String 3 s6: true
?String 3 n1: false
?String 3 n2: false
?String 3 n3: false
?String 3 n4: true
?String 3 ts1: true
?String 3 ts2: true
?String 3 ts3: true
?String 3 ts4: true
?String 3 ts5: true
?String 3 ts6: true
?String 3 xs1: true
?String 3 xs2: true
?String 3 xs3: true
?String 3 xs4: true
?String 3 xs5: true
?String 3 xs6: true
?String 4 s1: true
?String 4 s2: true
?String 4 s3: true
?String 4 s4: true
?String 4 s5: true
?String 4 s6: true
?String 4 n1: false
?String 4 n2: false
?String 4 n3: false
?String 4 n4: true
?String 4 ts1: true
?String 4 ts2: true
?String 4 ts3: true
?String 4 ts4: true
?String 4 ts5: true
?String 4 ts6: true
?String 4 xs1: true
?String 4 xs2: true
?String 4 xs3: true
?String 4 xs4: true
?String 4 xs5: true
?String 4 xs6: true
?(Int, Int, Int) 1 s1: true
?(Int, Int, Int) 1 s2: true
?(Int, Int, Int) 1 s3: true
?(Int, Int, Int) 1 s4: true
?(Int, Int, Int) 1 s5: true
?(Int, Int, Int) 1 s6: true
?(Int, Int, Int) 1 n1: false
?(Int, Int, Int) 1 n2: false
?(Int, Int, Int) 1 n3: false
?(Int, Int, Int) 1 n4: true
?(Int, Int, Int) 1 ts1: true
?(Int, Int, Int) 1 ts2: true
?(Int, Int, Int) 1 ts3: true
?(Int, Int, Int) 1 ts4: true
?(Int, Int, Int) 1 ts5: true
?(Int, Int, Int) 1 ts6: true
?(Int, Int, Int) 1 xs1: true
?(Int, Int, Int) 1 xs2: true
?(Int, Int, Int) 1 xs3: true
?(Int, Int, Int) 1 xs4: true
?(Int, Int, Int) 1 xs5: true
?(Int, Int, Int) 1 xs6: true
?(Int, Int, Int) 2 s1: true
?(Int, Int, Int) 2 s2: true
?(Int, Int, Int) 2 s3: true
?(Int, Int, Int) 2 s4: true
?(Int, Int, Int) 2 s5: true
?(Int, Int, Int) 2 s6: true
?(Int, Int, Int) 2 n1: false
?(Int, Int, Int) 2 n2: false
?(Int, Int, Int) 2 n3: false
?(Int, Int, Int) 2 n4: true
?(Int, Int, Int) 2 ts1: true
?(Int, Int, Int) 2 ts2: true
?(Int, Int, Int) 2 ts3: true
?(Int, Int, Int) 2 ts4: true
?(Int, Int, Int) 2 ts5: true
?(Int, Int, Int) 2 ts6: true
?(Int, Int, Int) 2 xs1: true
?(Int, Int, Int) 2 xs2: true
?(Int, Int, Int) 2 xs3: true
?(Int, Int, Int) 2 xs4: true
?(Int, Int, Int) 2 xs5: true
?(Int, Int, Int) 2 xs6: true
?(Int, Int, Int) 3 s1: true
?(Int, Int, Int) 3 s2: true
?(Int, Int, Int) 3 s3: true
?(Int, Int, Int) 3 s4: true
?(Int, Int, Int) 3 s5: true
?(Int, Int, Int) 3 s6: true
?(Int, Int, Int) 3 n1: false
?(Int, Int, Int) 3 n2: false
?(Int, Int, Int) 3 n3: false
?(Int, Int, Int) 3 n4: true
?(Int, Int, Int) 3 ts1: true
?(Int, Int, Int) 3 ts2: true
?(Int, Int, Int) 3 ts3: true
?(Int, Int, Int) 3 ts4: true
?(Int, Int, Int) 3 ts5: true
?(Int, Int, Int) 3 ts6: true
?(Int, Int, Int) 3 xs1: true
?(Int, Int, Int) 3 xs2: true
?(Int, Int, Int) 3 xs3: true
?(Int, Int, Int) 3 xs4: true
?(Int, Int, Int) 3 xs5: true
?(Int, Int, Int) 3 xs6: true
?(Int, Int, Int) 4 s1: true
?(Int, Int, Int) 4 s2: true
?(Int, Int, Int) 4 s3: true
?(Int, Int, Int) 4 s4: true
?(Int, Int, Int) 4 s5: true
?(Int, Int, Int) 4 s6: true
?(Int, Int, Int) 4 n1: false
?(Int, Int, Int) 4 n2: false
?(Int, Int, Int) 4 n3: false
?(Int, Int, Int) 4 n4: true
?(Int, Int, Int) 4 ts1: true
?(Int, Int, Int) 4 ts2: true
?(Int, Int, Int) 4 ts3: true
?(Int, Int, Int) 4 ts4: true
?(Int, Int, Int) 4 ts5: true
?(Int, Int, Int) 4 ts6: true
?(Int, Int, Int) 4 xs1: true
?(Int, Int, Int) 4 xs2: true
?(Int, Int, Int) 4 xs3: true
?(Int, Int, Int) 4 xs4: true
?(Int, Int, Int) 4 xs5: true
?(Int, Int, Int) 4 xs6: true
?(Int, String, Int) 1 s1: true
?(Int, String, Int) 1 s2: true
?(Int, String, Int) 1 s3: true
?(Int, String, Int) 1 s4: true
?(Int, String, Int) 1 s5: true
?(Int, String, Int) 1 s6: true
?(Int, String, Int) 1 n1: false
?(Int, String, Int) 1 n2: false
?(Int, String, Int) 1 n3: false
?(Int, String, Int) 1 n4: true
?(Int, String, Int) 1 ts1: true
?(Int, String, Int) 1 ts2: true
?(Int, String, Int) 1 ts3: true
?(Int, String, Int) 1 ts4: true
?(Int, String, Int) 1 ts5: true
?(Int, String, Int) 1 ts6: true
?(Int, String, Int) 1 xs1: true
?(Int, String, Int) 1 xs2: true
?(Int, String, Int) 1 xs3: true
?(Int, String, Int) 1 xs4: true
?(Int, String, Int) 1 xs5: true
?(Int, String, Int) 1 xs6: true
?(Int, String, Int) 2 s1: true
?(Int, String, Int) 2 s2: true
?(Int, String, Int) 2 s3: true
?(Int, String, Int) 2 s4: true
?(Int, String, Int) 2 s5: true
?(Int, String, Int) 2 s6: true
?(Int, String, Int) 2 n1: false
?(Int, String, Int) 2 n2: false
?(Int, String, Int) 2 n3: false
?(Int, String, Int) 2 n4: true
?(Int, String, Int) 2 ts1: true
?(Int, String, Int) 2 ts2: true
?(Int, String, Int) 2 ts3: true
?(Int, String, Int) 2 ts4: true
?(Int, String, Int) 2 ts5: true
?(Int, String, Int) 2 ts6: true
?(Int, String, Int) 2 xs1: true
?(Int, String, Int) 2 xs2: true
?(Int, String, Int) 2 xs3: true
?(Int, String, Int) 2 xs4: true
?(Int, String, Int) 2 xs5: true
?(Int, String, Int) 2 xs6: true
?(Int, String, Int) 3 s1: true
?(Int, String, Int) 3 s2: true
?(Int, String, Int) 3 s3: true
?(Int, String, Int) 3 s4: true
?(Int, String, Int) 3 s5: true
?(Int, String, Int) 3 s6: true
?(Int, String, Int) 3 n1: false
?(Int, String, Int) 3 n2: false
?(Int, String, Int) 3 n3: false
?(Int, String, Int) 3 n4: true
?(Int, String, Int) 3 ts1: true
?(Int, String, Int) 3 ts2: true
?(Int, String, Int) 3 ts3: true
?(Int, String, Int) 3 ts4: true
?(Int, String, Int) 3 ts5: true
?(Int, String, Int) 3 ts6: true
?(Int, String, Int) 3 xs1: true
?(Int, String, Int) 3 xs2: true
?(Int, String, Int) 3 xs3: true
?(Int, String, Int) 3 xs4: true
?(Int, String, Int) 3 xs5: true
?(Int, String, Int) 3 xs6: true
?(Int, String, Int) 4 s1: true
?(Int, String, Int) 4 s2: true
?(Int, String, Int) 4 s3: true
?(Int, String, Int) 4 s4: true
?(Int, String, Int) 4 s5: true
?(Int, String, Int) 4 s6: true
?(Int, String, Int) 4 n1: false
?(Int, String, Int) 4 n2: false
?(Int, String, Int) 4 n3: false
?(Int, String, Int) 4 n4: true
?(Int, String, Int) 4 ts1: true
?(Int, String, Int) 4 ts2: true
?(Int, String, Int) 4 ts3: true
?(Int, String, Int) 4 ts4: true
?(Int, String, Int) 4 ts5: true
?(Int, String, Int) 4 ts6: true
?(Int, String, Int) 4 xs1: true
?(Int, String, Int) 4 xs2: true
?(Int, String, Int) 4 xs3: true
?(Int, String, Int) 4 xs4: true
?(Int, String, Int) 4 xs5: true
?(Int, String, Int) 4 xs6: true
