base class Foo<T> {
  fun doIt(x: T): T;
}

class Bar<T>(x: T) extends Foo<T> {
  fun get(): T {
    this.x
  }
  fun doIt(x: T): T {
    x
  }
}

class Boom() extends Foo<Int> {
  fun doIt(x: Int): Int {
    x + 112
  }
}

fun matcher<T>(v: Foo<T>, y: T): T {
  v match {
  | x @ Bar _ -> x.doIt(x.get())
  | Boom _ -> y
  }
}

fun main(): void {
  x: Boom = Boom();
  _ = matcher(x, 5) + 5;
  print_string("Pass")
}
