fun main(): void {
  print_string("Pass")
}

base class Foo {
  type T default Int;
}

class Bar() extends Foo {
  fun num(): this::T {
    42
  }
}

class Baz() extends Foo {
  type T = String;
  fun str(): this::T {
    "42"
  }
}

base class Arry final () {
  type T: Test.MixedScalar default Test.MixedInt;
}

class Inty extends Arry {
  fun key(): this::T {
    Test.MixedInt(42)
  }
}

class Stringy extends Arry {
  type T = Test.MixedString;
  fun key(): this::T {
    Test.MixedString("")
  }
}
