/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

untracked fun main(): void {
  filename = arguments()[0];
  contents = FileSystem.readTextFile(filename);
  try {
    ast = SkipParse.parse(filename, contents);
    debug_json(ast);
  } catch {
  | e ->
    print_error(e.getMessage());
    exit(1)
  };
  void
}
